[project]
name = 'fluffy_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.emergency_stop_wallet]
path = 'contracts/emergency_stop_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
